define([], function() {
  return {
    TopFieldLabel: "Top/bottom",
    TopFieldOffText: "Bottom",
    TopFieldOnText: "Top",
    BasicGroupName: "Shape",
    ColorGroupName: "Color",
    CustomShapeGroupName: "Custom shape",
    HeightFieldLabel: "Height",
    PropertyPaneDescription: "Place this web part in a full-width section between two sections with different section background colors to create a shaped transition between the two sections. For the best effect, set the section's background color to match one of the two neighboring sections.",
    HorizontalFlipFieldLabel: "Direction",
    HorizontalFlipOnText: "Left to right",
    HorizontalFlipOffText: "Right to left",
  NumLayersFieldLabel: "Number of layers",
  NumWavesFieldLabel: "Number of waves",
  ShapeColorFieldName: "Next section color",
  ShapeColorNeutral: "Neutral",
  ShapeColorNone: "None",
  ShapeColorSoft: "Soft",
  ShapeColorStrong: "Strong",
  ShapeColorWarning: "If you set the next section's color to the same as this section's background color, your shape won't show up. Consider using another color.",
  ShapeCurve: "Curve",
  ShapeFieldLabel: "Shape",
  ShapeOffsetCurve: "Offset curve",
  ShapeOffsetTriangle: "Offset triangle",
  ShapeSlant: "Slant",
  ShapeTriangle: "Triangle",
  ShapeWave: "Wave",
  ShapeWaves: "Waves",
  ShapeCustom: "Custom",
  WidthFieldLabel: "Width",
  }
});
